import json

# Decoration suggestions based on cultural traditions, interior design styles, and atmosphere
decorations_db = {
    "AFG": "Koberce s geometrickými vzory, polštáře na zemi (toshak), mosazné tácy a konvice na čaj",
    "ALB": "Červeno-černé textilie, vyšívané ubrusy, dřevěné a kamenné prvky, tradiční koberce (qilim)",
    "DZA": "Berberské koberce, keramika s pestrými vzory, mozaikové lampy, nízké stolky",
    "AND": "Kamenné a dřevěné obložení (horský styl), rustikální nábytek, deky z ovčí vlny",
    "AGO": "Dřevěné sošky (masky), textilie se vzory Samakaka, proutěné koše",
    "ATG": "Tropické květiny, pestré látky (madras), mušle a mořské prvky",
    "ARG": "Kůže a hovězí kůže (cowhide rugs), prvky spojené s gaučos, stříbrné nádobí (mate), tango plakáty",
    "ARM": "Koberce s křížovými vzory, vyřezávané dřevo (chčkar motivy), granátová jablka (symbol) jako dekorace",
    "AUS": "Surfovací prkna, eukalyptové větve, aboriginské umění (tečkovaná malba), plážový styl",
    "AUT": "Alpský styl – dřevěné obložení, parohy, červeno-bílé kostkované ubrusy, květiny v oknech (muškáty)",
    "AZE": "Ázerbájdžánské koberce (tradiční vzory), měděné nádobí, čajové skleničky (armudu)",
    "BHS": "Pastelové barvy, mušle, palmové listy, námořnické prvky, junkanoo masky",
    "BHR": "Arabské lampy, perly (tradiční lov), tkané košíky, zlaté a krémové textilie",
    "BGD": "Textilie z juty, barevné rickshaw art (malby), terakotové sošky, rákosové rohože",
    "BRB": "Barvy moře a slunce, létající ryby (symbol), tropické rostliny, rumové soudky",
    "BLR": "Lněné ubrusy s červenou výšivkou, slaměné ozdoby (pavouci), dřevěné hračky",
    "BEL": "Secesní lampy, komiksové plakáty (Tintin), krajky (Bruggy), čokoládové fontány",
    "BLZ": "Mayské motivy, dřevěné řezby, tropické dřevo, houpací sítě",
    "BEN": "Voodoo symboly (umělecké sošky), barevné látky appliqués (Abomey), dřevěné masky",
    "BTN": "Barevné modlitební praporky, dřevěné vyřezávané prvky s draky, thangkas (malby na látce)",
    "BOL": "Látky aguayo (pruhované barevné textilie), lamí vlna, motivy And, barevné bambulky",
    "BIH": "Koberce (bosanski ćilim), měděné tepané nádobí (džezvy), dřevěný vyřezávaný nábytek",
    "BWA": "Proutěné košíky (Botswana baskets), kůže, hliněné nádoby, přírodní barvy savany",
    "BRA": "Pestré barvy karnevalu, tropická zeleň, houpací sítě, motivy Amazonie, fotbalové dresy",
    "BRN": "Islámská kaligrafie, zlaté textilie, mosazné kanóny (repliky), prvky vodních vesnic",
    "BGR": "Keramika s tradičními vzory (Trojan), vyšívané ubrusy, růžový olej a sušené růže",
    "BFA": "Bronzové sošky, batikované látky, masky z regionu Bobo, proutěné výrobky",
    "BDI": "Bubenické motivy (karyenda), přírodní materiály, rákosové rohože",
    "CPV": "Látky pano de terra, hudební nástroje jako dekorace (cavaquinho), sopečný kámen",
    "KHM": "Hedvábné šály (krama), sošky Apsar, motivy Angkor Vatu, stříbrné tepané krabičky",
    "CMR": "Sochy a masky z oblasti Grassfields, barevné textilie (toghu), dřevěné stoličky",
    "CAN": "Javorové listy, inuitské umění (soapstone carvings), kostkované flanelové vzory, hokejové dresy",
    "CAF": "Dřevěné masky, přírodní vlákna, motivy pralesa a motýlů (sběratelství)",
    "TCD": "Nomádské stany a koberce, kožené výrobky, pouštní motivy",
    "CHL": "Lapis lazuli (modrý kámen), textilie Mapuche, motivy moai (Velikonoční ostrov), víno",
    "CHN": "Červené lampiony, uzly štěstí, kaligrafie, čajové servisy, porcelán, draci",
    "COL": "Sombrero vueltiao, pestré barvy (Cartagena styl), květiny (orchideje), houpací sítě",
    "COM": "Vonné esence (ylang-ylang), vyřezávané dřevěné dveře, islámské a africké motivy",
    "COG": "Masky Punu, textilie raffia, dřevěné sošky",
    "COD": "Masky Kuba (geometrické vzory), malby v tzv. konžském populárním stylu, malachitové sošky",
    "CRI": "Dřevěné malované vozy (carretas), tropické motivy, kávová zrna jako dekorace",
    "CIV": "Masky Baule a Dan, textilie korhogo (malované blátem), tradiční tkalcovské stavy",
    "HRV": "Červeno-bílé kostky (šachovnice), levandule, kravaty (původ), motivy Jaderského moře",
    "CUB": "Stará auta (modely), doutníkové krabice, plakáty revoluce i hudby, koloniální styl (Havana)",
    "CYP": "Lefkarská krajka, mozaiky, olivové větve, keramika",
    "CZE": "Broušené sklo (křišťál), cibulák, modrotisk, folklorní stuhy, pivo a půllitry",
    "DNK": "Hygge styl – svíčky, měkké deky, minimalistický design, dřevo, světlé barvy",
    "DJI": "Proutěné košíky, nomádské prvky, motivy Rudého moře",
    "DMA": "Kreolské kroje (madras), motivy papoušků (sisserou), přírodní materiály",
    "DOM": "Larimar (modrý kámen), panenky bez tváře (Muñecas Limé), karnevalové masky",
    "ECU": "Panama klobouky (toquilla), látky s motivy And, sošky ze slonovinovce (tagua)",
    "EGY": "Papyrusy, sošky faraonů a koček, alabastrové lampy, koberce kilim",
    "SLV": "Mayské motivy, pestré houpací sítě, keramika z Ilobasca (miniatury)",
    "GNQ": "Dřevěné masky (Fang), motivy pralesa, košíkářství",
    "ERI": "Kávový obřad (jebena), proutěné košíky (mesob), tradiční látky",
    "EST": "Pletené vzory (rukavice), jalovcové dřevo, modro-černo-bílé kombinace",
    "ETH": "Kávový stolek (rekebot), barevné košíky (mesob), kříže Lalibela, textilie shemma",
    "FJI": "Tapa (látka z kůry - masi), misky na kavu (tanoa), květinové věnce",
    "FIN": "Moomin postavičky, finské sklo (Iittala design), březové dřevo, saunové doplňky",
    "FRA": "Eiffelovky, provensálské látky a levandule, plakáty z kaváren, móda a parfémy",
    "GAB": "Masky (Fang, Punu), kamenné sochy (Mbigou pierre), pralesní motivy",
    "GMB": "Batikované látky, dřevěné masky, motivy řeky a ptáků",
    "GEO": "Rohy na víno (kantsi), tradiční modré ubrusy, vlněné plstěné čepice",
    "DEU": "Tupláky na pivo, kukačkové hodiny, hrázděné domy (modely), vánoční ozdoby (Krušnohoří)",
    "GHA": "Látky Kente (pestré pruhy), stoličky Adinkra (symboly), korálky",
    "GRC": "Modro-bílá kombinace, řecké sochy a sloupy, olivovníky, oči proti uhranutí (mati)",
    "GRD": "Koření (muškátový oříšek) v miskách, karibské barvy, kakaové boby",
    "GTM": "Mayské textilie (pestré huipil), masky, keramika, quitapenas (panenky starostí)",
    "GIN": "Masky Nimba (symbol plodnosti), indigo textilie, bubny djembe",
    "GNB": "Dřevěné sošky (Bijagos), tkané textilie, motivy hrochů a moře",
    "GUY": "Dřevěné řezby, motivy deštného pralesa a vodopádů (Kaieteur), proutí",
    "HTI": "Naivní umění (pestré obrazy), kovové tepané dekorace (z barelů), voodoo symboly",
    "HND": "Mayské ruiny (Copán), keramika Lenca, dřevěné a kožené výrobky",
    "HUN": "Výšivky (Matyó), papriky (sušené svazky), malovaný porcelán (Herend, Zsolnay)",
    "ISL": "Ovčí kůže, lávové kameny, motivy polární záře, pletené vzory (lopapeysa)",
    "IND": "Sárí jako závěsy, mandaly, mosazné sošky bohů, vonné tyčinky, barevné polštáře",
    "IDN": "Batikované látky, loutky wayang (stínové divadlo), dřevěné masky, ratanový nábytek",
    "IRN": "Perské koberce, kaligrafie, miniatury, tyrkysové dlaždice, polštáře na sezení",
    "IRQ": "Datlové palmy (motivy), sumerské a babylonské reliéfy (repliky), měděné tácy",
    "IRL": "Trojlístky, keltské uzly a kříže, zelená barva, motivy harfy, ovčí vlna",
    "ISR": "Menory, dřevo olivovníku, judaika, hamsa (ruka Fatimy/Miriam), mozaiky",
    "ITA": "Benátské masky, renesanční umění, toskánská terakota, motivy vína a citronů",
    "JAM": "Rastafari barvy (zelená, žlutá, červená), hudební plakáty (reggae), dřevo",
    "JPN": "Origami, bonsaje, lampiony, noren (závěsy), tatami rohože, minimalismus",
    "JOR": "Mozaiky, lahve s pískem (Petra), beduínské stany a textilie, keramika",
    "KAZ": "Jurty (modely), plstěné koberce (shyrdak), motivy stepi a koní, dombra",
    "KEN": "Masajské deky (shuka), korálkové šperky, dřevěné sošky zvířat (safari), kisii stone",
    "KIR": "Tkané rohože, mušle, motivy oceánu a Vánoc (Kiritimati)",
    "PRK": "Propagační plakáty (retro styl), motivy kimilskungie, strohý socialistický realismus",
    "KOR": "Papír Hanji (lampy), celadonová keramika, masky Hahoe, tradiční uzly (maedeup)",
    "KWT": "Sadu (beduínské tkaní), modely lodí (dhow), vodárenské věže (symbol), luxusní koberce",
    "KGZ": "Jurty, plstěné koberce (shyrdak), motivy hor a koní, kalpak (klobouk) jako dekorace",
    "LAO": "Hedvábné látky (sinh), bambusové košíky na rýži, sošky Buddhy, lampiony",
    "LVA": "Jantar, lněné textilie, pletené rukavice s vzory (Lielvarde pás), dřevo",
    "LBN": "Cedrové dřevo, fénické sklo, blízkovýchodní lampy, intarzie",
    "LSO": "Slaměné klobouky (mokorotlo), deky Basotho (vzorované vlněné), hliněné výrobky",
    "LBR": "Dřevěné masky, látky country cloth (ručně tkané), palmové listy",
    "LBY": "Beduínské koberce, kožené výrobky, motivy římských ruin (Leptis Magna)",
    "LIE": "Alpské motivy, poštovní známky (slavné), knížecí korunky, víno",
    "LTU": "Jantar, lněné ubrusy, dřevěné kříže a sochy, proutěné košíky",
    "LUX": "Hrady a zámky (obrazy), víno a sklo z údolí Mosely, ocelářské motivy (historie)",
    "MDG": "Baobaby (sošky), rafie (vlákno), vyšívané ubrusy, vanilkové lusky",
    "MWI": "Dřevěné řezbářství (náčelnická křesla), proutěné rohože, batik",
    "MYS": "Batikované látky, cínové předměty (Royal Selangor), drak (wau), ratan",
    "MDV": "Lakované dřevěné krabičky, rohože thundu kunaa, mušle (kypraea), mořské motivy",
    "MLI": "Látka bogolan (mud cloth), masky Dogonů, sošky z Timbuktu",
    "MLT": "Krajky (bizzilla), maltézský kříž, foukané sklo (Mdina), vápencové prvky",
    "MHL": "Pletené košíky (kili), námořní mapy z klacíků, mušlové ozdoby",
    "MRT": "Kožené polštáře, stříbrné šperky, čajové servisy, pouštní stany",
    "MUS": "Modely lodí, pestrá země (Chamarel - písek v lahvích), dodo (postavičky)",
    "MEX": "Papel picado (vystřihovánky), lebky (Dia de los Muertos), kaktusy, sombrera, pestré deky",
    "FSM": "Dřevěné řezby (prostory pro setkávání), kamenné peníze (Yap - repliky), mušle",
    "MDA": "Tkané koberce s růžemi, vinná réva a sudy, keramika, vyšívané halenky",
    "MCO": "Kasino žetony, formule 1, luxusní jachty (modely), knížecí symboly",
    "MNG": "Jurta (ger) prvky, koňské žíně (morin khuur), plstěné výrobky, motivy Čingischána",
    "MNE": "Kamenné domy (motivy), hory a moře, Њegoš mauzoleum, tradiční krojové čepice",
    "MAR": "Posezení na polštářích, barevné dlaždice (zellige), tagine nádoby, lucerny, koberce",
    "MOZ": "Dřevěné sošky (Makonde - propletené postavy), capulana (látky), kokosové ořechy",
    "MMR": "Lakované misky, deštníky z Patheinu, loutky, zlaté pagody (obrazy)",
    "NAM": "Drahokamy a minerály, dřevěné řezby, motivy pouště a zvířat, proutí",
    "NRU": "Fosfátové skály (motivy), rybářské sítě, ptáci (fregatky)",
    "NPL": "Modlitební vlajky, mísy na zpívání, sošky Buddhy, thangky, motivy Himálaje",
    "NLD": "Tulipány, dřeváky, modrá keramika (Delft), větrné mlýny, oranžová barva",
    "NZL": "Maorské řezby (tiki), kapradiny (silver fern), paua mušle, ovčí kůže",
    "NIC": "Houpací sítě, keramika, sopečné kameny, pestré masky",
    "NER": "Šperky Tuaregů (stříbro), kožené výrobky, pouštní motivy",
    "NGA": "Yorubské korálkové koruny, látky adire, bronzové hlavy (Benin), masky",
    "MKD": "Ochridské perly, filigránové šperky, byzantské ikony, červené papriky",
    "NOR": "Trollové, vikingské lodě, sobí kůže, rosetmaling (malovaný nábytek)",
    "OMN": "Kadidlo a kadidelnice, dýky khanjar (na zdi), stříbrné šperky, pevnosti",
    "PAK": "Pestrobarvené náklaďáky (art), koberce, onyxové vázy, islámská kaligrafie",
    "PLW": "Storyboards (dřevěné vyřezávané příběhy), želví krunýře (imitace), mořské motivy",
    "PAN": "Molas (textilie Kuna indiánů), panamský průplav (historické mapy), klobouky",
    "PNG": "Masky z oblasti Sepik, bilum (pletené tašky), rajské ptactvo, kmenové štíty",
    "PRY": "Krajka ñandutí (pavoučí síť), dřevo, keramika, yerba maté soupravy",
    "PER": "Lamy a alpaky (plyšáci/obrazy), incké vzory, barevné textilie, keramika",
    "PHL": "Capiz mušle (lampy, okna), jeepney (modely), ratanový nábytek, perly",
    "POL": "Wycinanki (vystřihovánky), boleslawiecká keramika (tečky), jantar, folklorní vzory",
    "PRT": "Azulejos (modré kachličky), korek, kohout z Barcelos, fado kytary",
    "QAT": "Jestřábi (sokolnictví), perly, islámské umění, geometrické vzory, dhow lodě",
    "ROU": "Keramika Horezu, vyšívané haleny (ia), transylvánské motivy, malovaná vajíčka",
    "RUS": "Matrjošky, samovary, chochloma (malované dřevo), šátky, bříza",
    "RWA": "Agaseke (mírové košíky), imigongo (geometrické malby hnojem/hlínou), dřevěné štíty",
    "KNA": "Batik, kokosové ořechy, karibský styl, pevnost Brimstone Hill",
    "LCA": "Dřevěné papoušky (Jacquot), madras látky, motivy Pitons (hory)",
    "VCT": "Mořské plody, slaměné výrobky, motivy sopek a pláží",
    "WSM": "Tapa (siapo), misky na kavu, tetovací vzory jako dekorace, rohože",
    "SMR": "Tři věže (Guaita atd.), keramika, známky, středověký styl",
    "STP": "Kakao a káva, želví krunýře, tropické dřevo",
    "SAU": "Sadu (tkaní), arabské koberce, zlaté palmy, kadidelnice, stany",
    "SEN": "Obrazy z písku, malby na skle (sous-verre), košíky, sošky",
    "SRB": "Pirot koberce, ikony, tradiční kroje (jelek), " + '"' + "Sveti Sava" + '"' + " motivy",
    "SYC": "Coco de Mer (vzor ořechu), želvy, mořské barvy, vanilka",
    "SLE": "Batik, dřevěné masky, proutěné výrobky, „country cloth“",
    "SGP": "Peranakan dlaždice, merlion, orchideje, moderní futuristické prvky (Gardens by the Bay)",
    "SVK": "Črpáky (dřevěné poháry), modrotisk, valašky, výšivky, kukuřičné šustí",
    "SVN": "Včelí úly (malovaná čela), idrijská krajka, dračí motivy (Ljubljana), sklo",
    "SLB": "Dřevěné řezby se vkládanou perletí (nguzunguzu), válečné kánoe, tkané tašky",
    "SOM": "Proutěné koše a nádoby (dhiil), textilie, kadidlo",
    "ZAF": "Korálkové umění (Ndebele), pštrosí vejce, motivy Nelsona Mandely, protea (květina)",
    "SSD": "Proutěné výrobky, dřevěné sošky, korálky, pastevecké motivy",
    "ESP": "Vějíře, kastaněty, Gaudí mozaiky, keramika, plakáty býčích zápasů",
    "LKA": "Masky (Raksha), batika, čajové plantáže (obrazy), sloni, drahokamy",
    "SDN": "Ebenové dřevo, kožené výrobky, ibišek, nubijské pyramidy",
    "SUR": "Dřevěné řezbářství (Maroon art), pestré látky, tropické prvky",
    "SWE": "Dala koníci, sklo, minimalistický design, losí parohy, svícny",
    "CHE": "Kravské zvonce, švýcarské nože, hodiny, horské chaty (chalet style)",
    "SYR": "Damašský brokát, mozaikové krabičky, mýdlo z Aleppa (dekorativní), sklo",
    "TWN": "Lampiony, čajové servisy, nefrit, bambus, technologické prvky",
    "TJK": "Suzani (vyšívané textilie), dřevěné sloupy, horské motivy, čajchana styl",
    "TZA": "Tinga Tinga (pestré malby), ebenové sošky (Makonde), masajské deky, korálky",
    "THA": "Zlaté sošky Buddhy, orchideje, thajské hedvábí, trojúhelníkové polštáře, sloni",
    "TLS": "Tais (tkané látky), řezbářství, kávové motivy, krokodýlí legendy",
    "TGO": "Hliněné sošky, batik, fetiše (trh v Lomé), dřevěné stoličky",
    "TON": "Tapa (ngatu), rohože (taʻovala), velrybí motivy, dřevěné řezby",
    "TTO": "Steel pan (bubny), karnevalové kostýmy (peří), kolibříci, asfaltové jezero",
    "TUN": "Modro-bílá keramika, koberce (Kairouan), ptačí klece (Sidi Bou Said), mozaiky",
    "TUR": "Turecké lampy, koberce (kilim), nazar (modré oko), keramika z Izniku, čajové sety",
    "TKM": "Turkmenské koberce (Bokhara), achaltekinští koně (motivy), stříbrné šperky",
    "TUV": "Mušlové náhrdelníky, pletené vějíře, modely kánoí, známky",
    "UGA": "Kůra stromů (bambusová látka), košíky, gorilí motivy, bubny",
    "UKR": "Vyšívané košile (vyšyvanka), malovaná vajíčka (pysanka), slunečnice, obilí",
    "ARE": "Zlaté a mramorové prvky, arabská kaligrafie, modely mrakodrapů, koberce",
    "GBR": "Union Jack polštáře, červené telefonní budky, čajové konvice, královská rodina",
    "USA": "Neonové nápisy, vintage plechové cedule, hollywoodské hvězdy, route 66, patchwork",
    "URY": "Mate kalabasy, gaučo klobouky, tango, art deco prvky, ametysty",
    "UZB": "Suzani, keramika (Rishtan), ikat vzory (látky), dřevěné vyřezávané sloupy",
    "VUT": "Písečné kresby, dřevěné tam-tamy (bubny), masky, proutěné skoky (land diving)",
    "VAT": "Náboženské ikony, repliky soch (Michelangelo), vatikánská garda (figurky)",
    "VEN": "Houpací sítě (chinchorro), masky (Diablos de Yare), tepui (Stolové hory), kakao",
    "VNM": "Bambus, rýžové klobouky (nón lá), akvarely na hedvábí, lampiony (Hoi An), lakované misky",
    "YEM": "Barevná skla (qamariya), zakřivené dýky (jambiya), hliněné domy (model), koření",
    "ZMB": "Měděné výrobky (náramky, misky), košíkářství (Tonga baskets), masky",
    "ZWE": "Kamenné sochy (Šona), batik, proutěné košíky, motivy Viktoriiných vodopádů"
}

file_path = 'countries.json'

try:
    with open(file_path, 'r', encoding='utf-8') as f:
        countries = json.load(f)

    updated_count = 0
    for country in countries:
        code = country.get('cca3')
        # Initialize culture object if missing
        if 'culture' not in country:
            country['culture'] = {}
            
        # Get decoration from our DB, or use a default if not found
        # (Though we covered most, some might be missing - will leave null/empty if missing 
        # so frontend can handle it or use a very generic fallback if preferred, 
        # but user asked to populate it specifically).
        decoration = decorations_db.get(code)
        
        if decoration:
            country['culture']['decoration'] = decoration
            updated_count += 1
        else:
            # If we don't have a specific decoration, we might leave it or set a Generic one?
            # User said "projdi mi vsechny staty a dopln", implying I should try to have something.
            # But I don't have DB entry for every single island.
            # I will set it to None if not found, to avoid "Generic Decoration".
             country['culture']['decoration'] = None

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(countries, f, indent=4, ensure_ascii=False)

    print(f"Updated decorations for {updated_count} countries.")

except Exception as e:
    print(f"Error: {e}")
